name: Build the main branch
on: 
  push:
    branches: [ "main", "release-*" ]
    paths:
      - 'framework/app-service/**'
      - '!framework/app-service/.olares/**'
      - '!framework/app-service/README.md'
      - '!framework/app-service/PROJECT'
  pull_request:
    branches: [ "main", "release-*" ]
    paths:
      - 'framework/app-service/**'
      - '!framework/app-service/.olares/**'
      - '!framework/app-service/README.md'
      - '!framework/app-service/PROJECT'
defaults:
  run:
    working-directory: framework/app-service
jobs:
  build0-main:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y btrfs-progs libbtrfs-dev
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.24.6'
      - run: make build
