name: Backup Server Build test

on:
  push:
    branches: 
      - "module-backup"
    paths:
      - 'framework/backup-server/**'
      - '!framework/backup-server/.olares/**'
      - '!framework/backup-server/README.md'
  pull_request:
    branches: 
      - "module-backup"
    paths:
      - 'framework/backup-server/**'
      - '!framework/backup-server/.olares/**'
      - '!framework/backup-server/README.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '1.21.10'
    - name: Run Build
      run: |
        make all
        working-directory: framework/backup-server