name: Release Daemon

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
      ref:
        type: string
      repository:
        type: string
      release-id:
        type: string
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
      ref:
        type: string
      repository:
        type: string
      release-id:
        type: string

jobs:
  goreleaser:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          ref: ${{ inputs.ref }}
          repository: ${{ inputs.repository }}

      - name: Add Local Git Tag For GoReleaser
        run: git tag ${{ inputs.version }}
        continue-on-error: true

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.24.11

      - name: Setup Multi-arch for ARM64 libraries
        run: |
          sudo dpkg --add-architecture arm64
          sudo sed -i 's|deb http|deb [arch=amd64] http|g' /etc/apt/sources.list.d/*.list || true
          sudo sed -i 's|deb http|deb [arch=amd64] http|g' /etc/apt/sources.list || true
          echo "deb [arch=arm64] http://ports.ubuntu.com noble main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list
          echo "deb [arch=arm64] http://ports.ubuntu.com noble-updates main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list
          echo "deb [arch=arm64] http://ports.ubuntu.com noble-security main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list

      - name: Install dependencies and cross-compilers
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libudev-dev libpcap-dev
          sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
          sudo apt-get install -y libudev-dev:arm64 libpcap-dev:arm64

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3.1.0
        env:
          OLARES_RELEASE_ID: ${{ inputs.release-id }}
          CC_linux_arm64: aarch64-linux-gnu-gcc
          CXX_linux_arm64: aarch64-linux-gnu-g++
        with:
          distribution: goreleaser
          workdir: './daemon'
          version: v1.18.2
          args: release --clean

      - name: Upload to CDN
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
        run: |
          cd daemon/output && for file in $(ls *.tar.gz | grep -v no-release-id); do
            aws s3 cp "$file" s3://terminus-os-install${{ secrets.REPO_PATH }}${file} --acl=public-read
          done
